### ISSUE TITLE
Skrivefeil i oppgavetekster / feil i fasit?

### ISSUE THREAD

**Issue by andersvold** [bekk/funksjonell-frontend#21]
Hei!
Jobber med oppgavene på filter og map og finner noe som bør rettes:
Tekstoppgaven task 4:
`//that squares all arguments in the array.`

Stemmer ikke overens med funksjonens navn og testen: multiplyWithIndex(array) 

```
//TASK 5
//Create a function that uses array.map and array.filter
//to return a new list with all odd squares of the arguments.
function getOddSquares(array)

testArray([16,4,4], getOddSquares([4,5,2,3,1,2]), 5);
```

Her er teksten uklar: Er det tall med index som er odde, eller er det value?
Jeg antok det var index, og min løsning fungerer ikke med testen. Kan testen være feil?

Slik løste jeg:

```
function getOddSquares(array){
   return (array.filter( (val,index) => index % 2 !== 0)).map(val => val*val);
}
```

Dette ble resultatet
`"Test 5 failed: expected [16,4,4], got [25,9,4]"`

**Comment by simenstoa** [comment]
Takk for tilbakemelding. Oppgavetekstene er nå rettet opp. I oppgave 5 skulle det være 

```
//TASK 5
//Create a function that uses array.map and array.filter
//to return a new list with all even squares of the arguments.
//This means that if 6 is an element in the list, the resulting list
//should contain 36, which is the square of 6 and an even number :)
function getEvenSquares(array)

testArray([16,4,4], getEvenSquares([4,5,2,3,1,2]), 5);
```
