### ISSUE TITLE
Ordlyden i Task 8 

### ISSUE THREAD

**Issue by carljoachim** [bekk/funksjonell-frontend#3]
Simon: Veldig bra oppgavesett! Sitter og går igjennom nå og stusset bare litt på Task 8. Siden Task 7 filtrerer på de med mer enn 2 Oscars, og man ønsker å vise "total amount of Oscars" i bunnen av Actors componenten, burde ikke da strengen enten vise det antallet man har filtrert, eller fjerne filteret og vise alle? (+ at jeg tror det er totalt 12 oscars og ikke 13 ) :stuck_out_tongue_closed_eyes:

**Comment by ewendel** [comment]
Enig der, både at oppgavene er bra og at man kanskje bør fjerne filtreringen igjen i oppgave 9..?

**Comment by Tordensky** [comment]
@cjrorvik Takk for tilbakemeldinger. Skal rette det opp til onsdag.

**Comment by Tordensky** [comment]
Starter teksten med å be de fjerne filteret fra oppgave 7
