### ISSUE TITLE
Card komponent

### ISSUE THREAD

**Issue by carljoachim** [bekk/funksjonell-frontend#4]
(burde settes til props.card og ikke props.data kanskje  ) :see_no_evil: 
- When props.data.open is set to false, render an image using the URL cardBacksideUrl rather than the URL from props.data.item. Remember that you can test different states by changing the values in the game object.
- If props.data.matched is set to true, add the className matched to the card <div>
  Add "matched" som en tillegg til className="card" ikke sant?

**Comment by Tordensky** [comment]
Fixed. =)
