### ISSUE TITLE
Increase Card margin css

### ISSUE THREAD

**Issue by carljoachim** [bekk/funksjonell-frontend#5]
.card {
    margin: 30px;
} 

Fikk inntrykk av at det så litt bedre ut med 30px margin på kortene. Hvis ikke så gled de bare over i hverandre

**Comment by Tordensky** [comment]
Resulatet skal være som bildet under. Det var litt uklart i oppgavetekst med den image tagen i `<card>` componenten. Dersom man ikke satt className direkte på img elementet kunne kortene skli litt over hverandre. Har prøvd å gjøre det litt klarere i oppgaveteksten nå med at man ikke trenger å wrappe img i en div.

Gjør ikke noen endringer i stylingen på den.

![result](https://cloud.githubusercontent.com/assets/1482008/13791306/b931902a-eaec-11e5-8b66-0477db6fb6d9.png)
